# Numpy

## What is Numpy?

Open source numerical library used for working with mathematical functions with multi-dimensional array and matrix data structures.

## Why use Numpy?

Numpy arrays use less memory than normal python lists.

## Import Numpy

To import numpy do the following:

In [ ]:
import numpy as np

# Numpy Arrays


*   Converting existing objects to arrays
*   Using numpy functions to generate arrays
*   Creating arrays and matrices of random values
*   Basic array attributes





## np.array()
Generate a numpy array:

In [ ]:
nested_list = [[1, 2], [3, 4], [5, 6]]
nested_list

[[1, 2], [3, 4], [5, 6]]

In [ ]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

## np.arange(initial value, final value, step size)

Generate an array with predetermined set of numbers:


In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## np.zeros(x, y) and np.ones(x, y)
Generate a numpy array of 0's and 1's:

In [ ]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.linspace()

np.linspace(initial value, final value, number of elements wanted evenly spaced)

In [ ]:
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

## np.eye(array shape)
Generate a numpy array with a 1 on the diagonal:

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## np.random.rand(# of elements)
Generate a numpy array with random numbers from 0 to 1:


In [ ]:
np.random.rand(3)

array([0.4283336 , 0.90524654, 0.65139079])

## np.random.rand(x, y)
To create a matrix with random numbers ranging from 0 to 1:

In [ ]:
np.random.rand(3, 3)

array([[0.77999875, 0.97135081, 0.9153352 ],
       [0.17751134, 0.46694534, 0.12059376],
       [0.60036447, 0.36125856, 0.3911036 ]])

## np.random.randn(x, y)
To create a matrix of random negative & positive numbers:

In [ ]:
np.random.randn(2, 2)

array([[ 1.00798778, -0.98731183],
       [ 0.04809523,  1.19919465]])

## np.random.randint(initial value, final value, # of guesses or array shape)
To generate random numbers:


In [ ]:
np.random.randint(0, 19, (4, 4))

array([[11, 12,  1,  9],
       [16,  2, 17, 18],
       [ 5,  7,  8, 14],
       [ 7,  1,  1, 18]])

## np.random.seed(number)
To generate the same random number everytime the cell is run:



In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## np.reshape(x, y)
To reshape and reasign existing array:

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.shape

(5, 5)

## .max() and .min()
To get the max & min value of an array:

In [ ]:
ranarr = np.random.randint(0, 30, 15) 
ranarr

array([23, 11, 29,  5,  1, 27, 20,  0, 11, 25, 21, 28, 11, 24, 16])

In [ ]:
ranarr.max()

29

In [ ]:
ranarr.min()

0

## .argmax() and .argmin()
To get the position of the element of an array:

In [ ]:
ranarr.argmax()

2

In [ ]:
ranarr.argmin()

7

## .dtype
To grab the data type of an array:

In [ ]:
ranarr.dtype

dtype('int64')

# Numpy Index Selection


*   Grabbing single element
*   Grabbing a slice of elements
*   Broadcasting selections
*   Indexing and selection in 2-dimensions
*   Conditional Selection



## Single Element [#]
To grab a single element:

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[3]

3

## Slice of elements [# : #]
To grab a slice of elements:

In [ ]:
arr[2: 6]

array([2, 3, 4, 5])

In [ ]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr[7:]

array([ 7,  8,  9, 10])

## Broadcasting [# : #] = new value
With this feature we can assign new values of an existing array:

In [ ]:
arr[0:4] = 100
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

## Indexing a 2D Array

In [ ]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[2, 1]

40

In [ ]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection
With this feature we can set conditions to return a numpy array of boolean values and filter an array

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

# Numpy Operations
With this feature we can conduct simple mathematical operations on our numpy arrays

In [ ]:

arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.mean(arr)

5.0

In [ ]:
np.sum(arr)

55

In [ ]:
arr.max()

10

In [ ]:
arr.var()

10.0

In [ ]:
arr.std()

3.1622776601683795

In [ ]:
arr2d = np.arange(0, 25).reshape(5, 5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.sum()

300

In [ ]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])